server:
  port: 7000
spring:
  application:
    name: Postgres-Demo
  datasource:
    url: jdbc:postgresql://localhost:5432/employees
    username: postgres
    platform: postgres
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

